### ISSUE TITLE
关于多参数调用的疑问

### ISSUE THREAD

**Issue by HANKAIluo** [noahlam/mpvue-toast#1]
你好，我用
this.$mptoast('请输入正确网址，如xxxx.com', 'none', 3000)调用的时候会出现<motoast>组件闪一下，不出提示框的情况，用对象调用的时候提示框正常，请问你有遇见过这种情况吗？

**Comment by noahlam** [comment]
@HANKAIluo  不好意思,最近比较忙,才看到.

你描述的问题,是1.1.1版本的一个bug,目前已经修复.请更新至最新版本 1.1.3

```
npm i mptoast@1.1.3  -D
```
