### ISSUE TITLE
在main.js注册报错

### ISSUE THREAD

**Issue by anfisherman** [noahlam/mpvue-toast#2]
thirdScriptError 
 sdk uncaught third Error 
 Object(...) is not a function 
 TypeError: Object(...) is not a function

完全按照步骤来的，麻烦有时间看下谢谢！

**Comment by pokerII** [comment]
文档上的 
```
import mpVueToastRegistry from 'mptoast';
```

改为

``` 
import mpVueToastRegistry from 'mptoast/registry';
```

**Comment by omretterry** [comment]
同样遇到了，2楼方案，仍有问题

**Comment by omretterry** [comment]
已解决，未注意2楼大小写问题
