### ISSUE TITLE
没有挂载节点的toast该如何实现呢

### ISSUE THREAD

**Issue by zhengpan** [noahlam/mpvue-toast#4]
这个mptoast都是依赖于page里的组件模板挂载。如果是fly请求之后的提示该如何实现呢

**Comment by noahlam** [comment]
没地方挂载,是无法实现的.不过mptoast是基于vuex的,也就是说,不管你再哪个地方执行 this.$mptoast(),只要你当前页面里面有<mptoast />节点,就会显示提示信息..
